module.exports = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  FORBIDDEN: 'FORBIDDEN',
  USER_NAME_CONFLICT: 'USER_NAME_CONFLICT',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  REQUEST_NOT_FOUND: 'REQUEST_NOT_FOUND',
  STATE_CONFLICT: 'STATE_CONFLICT',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INIT_CONFIG_MISSING: 'INIT_CONFIG_MISSING',
  STORE_WRITE_FAILED: 'STORE_WRITE_FAILED',
};