export const ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  FORBIDDEN: 'FORBIDDEN',
  USER_NAME_CONFLICT: 'USER_NAME_CONFLICT',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  REQUEST_NOT_FOUND: 'REQUEST_NOT_FOUND',
  STATE_CONFLICT: 'STATE_CONFLICT',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INIT_CONFIG_MISSING: 'INIT_CONFIG_MISSING',
  STORE_WRITE_FAILED: 'STORE_WRITE_FAILED',
};

export const ERROR_MESSAGES = {
  AUTH_INVALID_CREDENTIALS: '用户名或密码错误',
  AUTH_ACCOUNT_DISABLED: '账号已禁用，请联系管理员',
  AUTH_TOKEN_INVALID: '登录已过期，请重新登录',
  FORBIDDEN: '权限不足',
  USER_NAME_CONFLICT: '用户名已存在',
  USER_NOT_FOUND: '用户不存在',
  REQUEST_NOT_FOUND: '申请不存在',
  STATE_CONFLICT: '操作冲突，当前状态不允许此操作',
  VALIDATION_ERROR: '输入校验失败',
  INIT_CONFIG_MISSING: '系统配置缺失',
  STORE_WRITE_FAILED: '数据写入失败',
};